version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: avitotest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"